### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by zeplar-exe** [mrodz/receiptify#15]
- [x] Require an email and password input
- [x] Allow login with Google
- [x] Allow login with GitHub
- [x] Link to Signup Page
- [x] Firebase Integration
- [x] Password Reset Button (unimplemented)

**Comment by mrodz** [comment]
@zeplar-exe I added tailwind to the frontend to make styling easier. I made the login page responsive too. I moved away from the `create-react-app` structure because that project is no longer maintained and makes oversized bundles. Everything else is the same.
